
package PipePal;

import java.math.BigDecimal;
import java.text.DecimalFormat;

/**
 *
 * @author Daniel
 */
public class MenuB extends javax.swing.JFrame {

    /**
     * Creates new form MenuB
     */
    public MenuB() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        WCQ = new javax.swing.JSpinner();
        LVQ = new javax.swing.JSpinner();
        SHQ = new javax.swing.JSpinner();
        BTQ = new javax.swing.JSpinner();
        BGQ = new javax.swing.JSpinner();
        KSQ = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Totals = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Domestic Water Pipe Sizing");
        setLocation(new java.awt.Point(700, 300));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fixtures");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Water Closet");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Shower");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bath Tub");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Bath Group");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("TOTAL WSFU:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Kitchen Sink");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("PIPE SIZE:");

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {2.7, 1.5, 3.6},
                {0.5, 0.5, 0.7},
                {1.0, 1.0, 1.4},
                {1.0, 1.0, 1.4},
                {2.2, 0.0, 2.2},
                {1.0, 1.0, 1.4}
            },
            new String [] {
                "CW", "HW", "Total"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("CW");
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("HW");
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Total");
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Lavatory");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        WCQ.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        LVQ.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        SHQ.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        BTQ.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        BGQ.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        KSQ.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Quantity");

        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        String WCQStr = WCQ.getValue().toString();
        double WCQVal = Double.parseDouble(WCQStr);

        String LVQStr = LVQ.getValue().toString();
        double LVQVal = Double.parseDouble(LVQStr);

        String SHQStr = SHQ.getValue().toString();
        double SHQVal = Double.parseDouble(SHQStr);

        String BTQStr = BTQ.getValue().toString();
        double BTQVal = Double.parseDouble(BTQStr);

        String BGQStr = BGQ.getValue().toString();
        double BGQVal = Double.parseDouble(BGQStr);

        String KSQStr = KSQ.getValue().toString();
        double KSQVal = Double.parseDouble(KSQStr);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {BGQVal*2.7, BGQVal*1.5, BGQVal*3.6},
                {LVQVal*0.5, LVQVal*0.5, LVQVal*0.7},
                {SHQVal*1.0, SHQVal*1.0, SHQVal*1.4},
                {BTQVal*1.0, BTQVal*1.0, BTQVal*1.4},
                {WCQVal*2.0, WCQVal*0.0, WCQVal*2.2},
                {KSQVal*1.0, KSQVal*1.0, KSQVal*1.4}
            },
            new String [] {
                "CW", "HW", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(35);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setHeaderValue("CW");
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setHeaderValue("HW");
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Total");
        }

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enter Values");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Totals.setBackground(new java.awt.Color(255, 255, 204));
        Totals.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Totals.setForeground(new java.awt.Color(0, 0, 0));
        Totals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {0, 0, 0},
                {0, 0, 0},
                {0, 0, 0}
            },
            new String [] {
                "CW", "HW", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Totals.setRowHeight(35);
        jScrollPane3.setViewportView(Totals);
        if (Totals.getColumnModel().getColumnCount() > 0) {
            Totals.getColumnModel().getColumn(0).setResizable(false);
            Totals.getColumnModel().getColumn(0).setHeaderValue("CW");
            Totals.getColumnModel().getColumn(1).setResizable(false);
            Totals.getColumnModel().getColumn(1).setHeaderValue("HW");
            Totals.getColumnModel().getColumn(2).setResizable(false);
            Totals.getColumnModel().getColumn(2).setHeaderValue("Total");
        }

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("TOTAL GPM:");

        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WCQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LVQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SHQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BGQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KSQ, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WCQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(LVQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SHQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(BTQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BGQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KSQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addGap(9, 9, 9)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DecimalFormat df = new DecimalFormat("0.00");
        String WCQStr = WCQ.getValue().toString();
        double WCQVal = Double.parseDouble(WCQStr);
        
        String LVQStr = LVQ.getValue().toString();
        double LVQVal = Double.parseDouble(LVQStr);
        
        String SHQStr = SHQ.getValue().toString();
        double SHQVal = Double.parseDouble(SHQStr);
        
        String BTQStr = BTQ.getValue().toString();
        double BTQVal = Double.parseDouble(BTQStr);
        
        String BGQStr = BGQ.getValue().toString();
        double BGQVal = Double.parseDouble(BGQStr);
        
        String KSQStr = KSQ.getValue().toString();
        double KSQVal = Double.parseDouble(KSQStr);
        
        
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        {df.format(BGQVal*2.7), df.format(BGQVal*1.5), df.format(BGQVal*3.6)},
        {df.format(LVQVal*0.5), df.format(LVQVal*0.5), df.format(LVQVal*0.7)},
        {df.format(SHQVal*1.0), df.format(SHQVal*1.0), df.format(SHQVal*1.4)},
        {df.format(BTQVal*1.0), df.format(BTQVal*1.0), df.format(BTQVal*1.4)},
        {df.format(WCQVal*2.2), df.format(WCQVal*0.0), df.format(WCQVal*2.2)},
        {df.format(KSQVal*1.0), df.format(KSQVal*1.0), df.format(KSQVal*1.4)}
    },
    new String [] {
        "CW", "HW", "Total"
    }
) {
    boolean[] canEdit = new boolean [] {
        false, false, false
    };

    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
});
        double sumCW = 0;
    for (int i = 0; i < jTable2.getRowCount(); i++){
    sumCW = sumCW + Double.parseDouble(jTable2.getValueAt(i, 0).toString());
    }
        double sumHW = 0;
    for (int i = 0; i < jTable2.getRowCount(); i++){
    sumHW = sumHW + Double.parseDouble(jTable2.getValueAt(i, 1).toString());
    }
        double sumT = 0;
    for (int i = 0; i < jTable2.getRowCount(); i++){
    sumT = sumT + Double.parseDouble(jTable2.getValueAt(i, 2).toString());
    }
    
        double sizes[] = {0.5, 0.75, 1.0, 1.25, 1.5, 2.0};
        double index[] = {5.82, 12.00, 20.00, 31.00, 44.00 ,77.00};
        double sizeCW = 0.5;
        double sizeHW = 0.5;
        double sizeT = 0.5;     
        double gpmCW = -(Math.pow(2, -9*(Math.pow(sumHW, 6))))+(Math.pow(6, -7*(Math.pow(sumHW, 5))))-(Math.pow(7, -5*(Math.pow(sumHW, 4))))+0.0041*(Math.pow(sumHW, 3))-0.1238*(Math.pow(sumHW, 2))+2.2616*sumHW+0.8128;
        double gpmHW = -(Math.pow(2, -9*(Math.pow(sumHW, 6))))+(Math.pow(6, -7*(Math.pow(sumHW, 5))))-(Math.pow(7, -5*(Math.pow(sumHW, 4))))+0.0041*(Math.pow(sumHW, 3))-0.1238*(Math.pow(sumHW, 2))+2.2616*sumHW+0.8128;
        double gpmT = -(Math.pow(2, -9*(Math.pow(sumT, 6))))+(Math.pow(6, -7*(Math.pow(sumT, 5))))-(Math.pow(7, -5*(Math.pow(sumT, 4))))+0.0041*(Math.pow(sumT, 3))-0.1238*(Math.pow(sumT, 2))+2.2616*sumT+0.8128;
        for (int i = 0; i < index.length; i++){
        if (gpmCW >= index[i]){
        sizeCW = sizes[i];
            }
        if (gpmHW > index[i]){
        sizeHW = sizes[i];
            }
        if (gpmT > index[i]){
        sizeT = sizes[i];
            }
        }

        Totals.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        {df.format(sumCW), df.format(sumHW), df.format(sumT)},
        {
            df.format(gpmCW),
            df.format(gpmHW),
            df.format(gpmT)
        },
        {sizeCW, sizeHW, sizeT}
    },
    new String [] {
        "CW", "HW", "Total"
    }
) {
    boolean[] canEdit = new boolean [] {
        false, false, false
    };

    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
});
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainMenu().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner BGQ;
    private javax.swing.JSpinner BTQ;
    private javax.swing.JSpinner KSQ;
    private javax.swing.JSpinner LVQ;
    private javax.swing.JSpinner SHQ;
    private javax.swing.JTable Totals;
    private javax.swing.JSpinner WCQ;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
